### ISSUE TITLE
Error backup VM ovirt

### ISSUE THREAD

**Issue by cestila** [bareos/bareos-contrib#44]
Estoy utilizando el script para realizar backup de maquinas virtuales con ovirt y me da el siguiente error:

~~~
2019-10-23 19:10:50 bareos-dir JobId 660: Error: Bareos bareos-dir 18.2.5 (30Jan19):
  Build OS:               Linux-4.4.92-6.18-default redhat CentOS Linux release 7.6.1810 (Core) 
  JobId:                  660
  Job:                    backup-wservicio.2019-10-23_19.10.46_41
  Backup Level:           Full
  Client:                 "manager-fd" 18.2.5 (30Jan19) Linux-4.4.92-6.18-default,redhat,CentOS Linux release 7.6.1810 (Core) ,CentOS_7,x86_64
  FileSet:                "wservicio-fs" 2019-10-19 20:00:00
  Pool:                   "VM-Full" (From Job FullPool override)
  Catalog:                "MyCatalog" (From Client resource)
  Storage:                "SnapVM" (From Job resource)
  Scheduled time:         23-oct-2019 19:10:46
  Start time:             23-oct-2019 19:10:49
  End time:               23-oct-2019 19:10:50
  Elapsed time:           1 sec
  Priority:               10
  FD Files Written:       0
  SD Files Written:       0
  FD Bytes Written:       0 (0 B)
  SD Bytes Written:       0 (0 B)
  Rate:                   0.0 KB/s
  Software Compression:   None
  VSS:                    no
  Encryption:             no
  Accurate:               no
  Volume name(s):         VM-Full-0045
  Volume Session Id:      74
  Volume Session Time:    1571435910
  Last Volume Bytes:      638 (638 B)
  Non-fatal FD errors:    1
  SD Errors:              0
  FD termination status:  Fatal Error
  SD termination status:  Running
  Bareos binary info:     bareos.org build: Get official binaries and vendor support on bareos.com
  Termination:            *** Backup Error ***

2019-10-23 19:11:31 bareos-sd JobId 660: Releasing device "SnapVM" (/var/lib/bareos/storage).
2019-10-23 19:11:31 manager-fd JobId 660: Fatal error: filed/fd_plugins.cc:666 Command plugin "python:module_path=/usr/lib64/bareos/plugins:module_name=bareos-fd-ovirt:server=manager.muni.jk:username=admin@internal:password=Zse45tgbN:vm_name=wservicio:ca=/etc/pki/ovirt-engine/ca.pem" requested, but is not loaded.
2019-10-23 19:11:31 manager-fd JobId 660: Fatal error: python-fd: Traceback (most recent call last):
  File "/usr/lib64/bareos/plugins/BareosFdWrapper.py", line 38, in handle_plugin_event
    return bareos_fd_plugin_object.handle_plugin_event(context, event)
  File "/usr/lib64/bareos/plugins/BareosFdPluginOvirt.py", line 394, in handle_plugin_event
    return self.start_backup_job(context)
  File "/usr/lib64/bareos/plugins/BareosFdPluginOvirt.py", line 95, in start_backup_job
    return self.ovirt.prepare_vm_backup(context, self.options)
  File "/usr/lib64/bareos/plugins/BareosFdPluginOvirt.py", line 521, in prepare_vm_backup
    if not self.get_vm(context, options):
  File "/usr/lib64/bareos/plugins/BareosFdPluginOvirt.py", line 586, in get_vm
    res = self.vms_service.list(search=search, all_content=True)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py", line 34210, in list
    return self._internal_get(headers, query, wait)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 211, in _internal_get
    return future.wait() if wait else future
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 55, in wait
    return self._code(response)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 206, in callback
    return self._internal_read_body(response)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 319, in _internal_read_body
    return reader.Reader.read(response.body)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/reader.py", line 331, in read
    return reader(cursor)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/readers.py", line 17531, in read_many
    objs.append(VmReader.read_one(reader))
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/readers.py", line 17357, in read_one
    obj.creation_time = Reader.read_date(reader)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/reader.py", line 235, in read_date
    return Reader.parse_date(reader.read_element())
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/reader.py", line 217, in parse_date
    date = datetime.datetime.strptime(text, format)
TypeError: attribute of type 'NoneType' is not callable
~~~

tengo ovirt Version 4.2.8.2-1.el7
ovirt-engine-sdk-python 3.6.9.1-1.el7
bareos-filedaemon-python-plugin 18.2.5-144.1.el7
y los dos script del plugin de ovirt

python:module_path=/usr/lib64/bareos/plugins:module_name=bareos-fd-ovirt:server=manager.muni.jk:username=admin@internal:password=Zse45tgbN:vm_name=wservicio:ca=/etc/pki/ovirt-engine/ca.pem

**Comment by sduehr** [comment]
Qual version de python-ovirt-engine-sdk4 está instalado?
El error está arreglado por el siguiente commit:
https://github.com/oVirt/ovirt-engine-sdk/commit/ecc7c06d6794811a9b9763357ceea18481061d56
Pero no está incluido en
https://resources.ovirt.org/pub/ovirt-4.2/rpm/el7/x86_64/python-ovirt-engine-sdk4-4.2.9-2.el7.x86_64.rpm

Con https://resources.ovirt.org/pub/ovirt-4.3/rpm/el7/x86_64/python-ovirt-engine-sdk4-4.3.2-2.el7.x86_64.rpm debería que functionar, pero puede ser que hay problemas de compatibilidad con oVirt 4.2.

El almacenamiento debe que ser iSCSI (o FibreChannel) y preallocated, segun mi experiencia no functiona el plugin con almacenamient NFS o thin  provisioned.
